"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var vue_1 = require("vue");
var pinia_1 = require("pinia");
var router_1 = require("./router");
require("./assets/styles/tailwind.css");
var App_vue_1 = require("./App.vue");
var app = (0, vue_1.createApp)(App_vue_1.default);
var pinia = (0, pinia_1.createPinia)();
app.use(pinia);
app.use(router_1.default);
app.mount("#app");
